== Installation

NOTE: As a prerequisite for everything in this manual, you'll need to have one the major 3 Java IDEs (IntelliJ IDEA, NetBeans, or Eclipse) with the Codename One plugin installed.  For instructions on installing Codename One, see https://www.codenameone.com/download.html

The CodeRAD library is distributed as a cn1lib.  For more information about the *cn1lib* format, see https://www.codenameone.com/manual/advanced-topics.html#_libraries_cn1lib[the cn1libs section of the Codename One manual].

cn1libs need to be installed separately in each Codename One project in which they are used.  I.e. you don't install them globally.  Rather you install them in each individual project.  Therefore, the remainder of the instructions assume that you have already created a project.

[NOTE]
====
For instructions on creating a new project in your IDE, please follow the appopriate link below for your IDE:

. https://www.codenameone.com/how-do-i---create-a-basic-hello-world-application--send-it-to-my-device-using-intellij-idea.html[IntelliJ IDEA]
. https://www.codenameone.com/how-do-i---create-a-basic-hello-world-application--send-it-to-my-device-using-netbeans.html[NetBeans]
. https://www.codenameone.com/how-do-i---create-a-basic-hello-world-application--send-it-to-my-device-using-eclipse.html[Eclipse]
====

=== Activating CSS

CodeRAD uses CSS to provide styling for its components.  If you haven't already activated CSS in your project, you'll need to do that before installing the CodeRAD cn1lib.  See https://www.codenameone.com/blog/live-css-update.html[this tutorial] for instructions on activating CSS.

=== Installing the CodeRAD cn1lib

For instructions on installing cn1libs, see https://www.codenameone.com/blog/automatically-install-update-distribute-cn1libs-extensions.html[this tutorial].




