/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codename1.rad.schemas;

import com.codename1.rad.models.Tag;

/**
 * From https://schema.org/CreativeWork
 * @author shannah
 */
public interface CreativeWork extends Thing {
    public static final Tag about = new Tag("about"),
            abstract_ = new Tag("abstract"),
            accessMode = new Tag("accessMode"),
            accessModeSufficient = new Tag("accessModeSufficient"),
            accessibilityAPI = new Tag("accessibilityAPI"),
            accessibilityControl = new Tag("accessibilityControl"),
            accessibilityFeature = new Tag("accessibilityFeature"),
            accessibilityHazard = new Tag("accessibilityHazard"),
            accessibilitySummary = new Tag("accessibilitySummary"),
            accountablePerson = new Tag("accountablePerson"),
            aggregateRating = new Tag("aggregateRating"),
            alternativeHeadline = new Tag("alternativeHeadline"),
            associatedMedia = new Tag("associatedMedia"),
            audience = new Tag("audience"),
            audio = new Tag("audio"),
            author = new Tag("author"),
            
            award = new Tag("award"),
            character = new Tag("character"),
            citation = new Tag("citation"),
            
            comment = new Tag("comment"),
            commentCount = new Tag("commentCount"),
            conditionsOfAccess = new Tag("conditionOfAccess"),
            contentLocation = new Tag("contentLocation"),
            contentRating = new Tag("contentRating"),
            contentReferenceTime = new Tag("contentReferenceTime"),
            contributor = new Tag("contributor"),
            copyrightHolder = new Tag("copyrightHolder"),
            copyrightYear = new Tag("copyrightYear"),
            correction = new Tag("correction"),
            creativeWorkStatus = new Tag("creativeWorkStatus"),
            creator = new Tag("creator"),
            dateCreated = new Tag("dateCreated"),
            dateModified = new Tag("dateModified"),
            datePublished = new Tag("datePublished"),
            discussionUrl = new Tag("discussionUrl"),
            editor = new Tag("editor"),
            educationalAlignment = new Tag("educationalAlignment"),
            educationalUse = new Tag("educationalUse"),
            encoding = new Tag("encoding"),
            encodingFormat = new Tag("encodingFormat"),
            exampleOfWork = new Tag("exampleOfWork"),
            expires = new Tag("expires"),
            funder = new Tag("funder"),
            genre = new Tag("genre"),
            hasPart = new Tag("hasPart"),
            headline = new Tag("headline"),
            inLanguage = new Tag("inLanguage"),
            interactionStatistic = new Tag("interactionStatistic"),
            interactivityType = new Tag("interactivityType"),
            isAccessibleOrFree = new Tag("isAccessibleOrFree"),
            isBasedOn = new Tag("isBasedOn"),
            isFamilyFriendly = new Tag("isFamilyFriendly"),
            isPartOf = new Tag("isPartOf"),
            keywords = new Tag("keywords"),
            learningResourceType = new Tag("learningResourceType"),
            license = new Tag("license"),
            locationCreated = new Tag("locationCreated"),
            mainEntity = new Tag("mainEntity"),
            maintainer = new Tag("maintainer"),
            material = new Tag("material"),
            materialExtent = new Tag("materialExtent"),
            mentions = new Tag("mentions"),
            offers = new Tag("offers"),
            position = new Tag("position"),
            producer = new Tag("producer"),
            provider = new Tag("provider"),
            publication = new Tag("publication"),
            publisher = new Tag("publisher"),
            publisherImprint = new Tag("publisherImprint"),
            publishingPrinciples = new Tag("publishingPrinciples"),
            recordedAt = new Tag("recordedAt"),
            releasedEvent = new Tag("releasedEvent"),
            review = new Tag("review"),
            schemaVersion = new Tag("schemaVersion"),
            sdDatePublished = new Tag("sdDatePublished"),
            sdLicense = new Tag("sdLicense"),
            sdPublisher = new Tag("sdPublisher"),
            sourceOrganization = new Tag("sourceOrganization"),
            spatial = new Tag("spatial"),
            spatialCoverage = new Tag("spatialCoverage"),
            sponsor = new Tag("sponsor"),
            temporal = new Tag("temporal"),
            temporalCoverage = new Tag("temporalCoverage"),
            text = new Tag("text"),
            timeRequired = new Tag("timeRequired"),
            translationOfWork = new Tag("translationOfWork"),
            translator = new Tag("translator"),
            typicalAgeRange = new Tag("typicalAgeRange"),
            version = new Tag("version"),
            video = new Tag("video"),
            workExample = new Tag("workExample"),
            workTranslation = new Tag("workTranslation"),
            viewCount = new Tag("viewCount");
            
            
}
