/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codename1.rad.schemas;

import com.codename1.rad.models.Tag;

/**
 * From https://schema.org/CreativeWork
 * @author shannah
 */
public interface CreativeWork extends Thing {
    public static final Tag about = new Tag(),
            abstract_ = new Tag(),
            accessMode = new Tag(),
            accessModeSufficient = new Tag(),
            accessibilityAPI = new Tag(),
            accessibilityControl = new Tag(),
            accessibilityFeature = new Tag(),
            accessibilityHazard = new Tag(),
            accessibilitySummary = new Tag(),
            accountablePerson = new Tag(),
            aggregateRating = new Tag(),
            alternativeHeadline = new Tag(),
            associatedMedia = new Tag(),
            audience = new Tag(),
            audio = new Tag(),
            author = new Tag(),
            
            award = new Tag(),
            character = new Tag(),
            citation = new Tag(),
            
            comment = new Tag(),
            commentCount = new Tag(),
            conditionsOfAccess = new Tag(),
            contentLocation = new Tag(),
            contentRating = new Tag(),
            contentReferenceTime = new Tag(),
            contributor = new Tag(),
            copyrightHolder = new Tag(),
            copyrightYear = new Tag(),
            correction = new Tag(),
            creativeWorkStatus = new Tag(),
            creator = new Tag(),
            dateCreated = new Tag(),
            dateModified = new Tag(),
            datePublished = new Tag(),
            discussionUrl = new Tag(),
            editor = new Tag(),
            educationalAlignment = new Tag(),
            educationalUse = new Tag(),
            encoding = new Tag(),
            encodingFormat = new Tag(),
            exampleOfWork = new Tag(),
            expires = new Tag(),
            funder = new Tag(),
            genre = new Tag(),
            hasPart = new Tag(),
            headline = new Tag(),
            inLanguage = new Tag(),
            interactionStatistic = new Tag(),
            interactivityType = new Tag(),
            isAccessibleOrFree = new Tag(),
            isBasedOn = new Tag(),
            isFamilyFriendly = new Tag(),
            isPartOf = new Tag(),
            keywords = new Tag(),
            learningResourceType = new Tag(),
            license = new Tag(),
            locationCreated = new Tag(),
            mainEntity = new Tag(),
            maintainer = new Tag(),
            material = new Tag(),
            materialExtent = new Tag(),
            mentions = new Tag(),
            offers = new Tag(),
            position = new Tag(),
            producer = new Tag(),
            provider = new Tag(),
            publication = new Tag(),
            publisher = new Tag(),
            publisherImprint = new Tag(),
            publishingPrinciples = new Tag(),
            recordedAt = new Tag(),
            releasedEvent = new Tag(),
            review = new Tag(),
            schemaVersion = new Tag(),
            sdDatePublished = new Tag(),
            sdLicense = new Tag(),
            sdPublisher = new Tag(),
            sourceOrganization = new Tag(),
            spatial = new Tag(),
            spatialCoverage = new Tag(),
            sponsor = new Tag(),
            temporal = new Tag(),
            temporalCoverage = new Tag(),
            text = new Tag(),
            timeRequired = new Tag(),
            translationOfWork = new Tag(),
            translator = new Tag(),
            typicalAgeRange = new Tag(),
            version = new Tag(),
            video = new Tag(),
            workExample = new Tag(),
            workTranslation = new Tag(),
            viewCount = new Tag();
            
            
}
